version: "3.8"  # Can be removed as per warning, but won't cause issues
networks:
    application:
        driver: bridge

services:
    db:
        image: mysql:8.0  # Use a specific version instead of latest
        container_name: mysqlcontainer
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: qwepoi  # Must be set (change to something secure)
            MYSQL_DATABASE: image_gallery
            MYSQL_USER: image_gallery_user
            MYSQL_PASSWORD: qwepoi       # Should match root password or be different
        networks:
            - application
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpassword"]  # Update password here
            interval: 5s
            timeout: 5s
            retries: 30
        restart: unless-stopped

    app:
        build: .
        container_name: app
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        networks:
            - application
        volumes:
            - .:/app
        command: >
            sh -c "
            while ! mysqladmin ping -h db -u root -proot --silent; do sleep 1; done &&
            composer install &&
            php artisan migrate &&
            php artisan serve --host=0.0.0.0 --port=8000
            "
        restart: unless-stopped
