apiVersion: v1
kind: Service
metadata:
  name: image-gallery
  namespace: imagegallery-prod
spec:
  type: LoadBalancer
  selector:
    app: image-gallery
  ports:
    - name: http
      port: 80
      targetPort: http
